# Based on https://qxf2.com/blog/tox-with-circleci/
version: 2
jobs:
  test:
      docker:
        - image: themattrix/tox
      steps:
        - checkout
        - run: sudo apt-get -y install ipython
        - run: pip install jupyter --user
        - run: pip install -r requirements.txt --user
        # - run: pytest -s --junitxml=test_results/pytest/pytest-report.xml
        - run: tox
        - store_test_results:
            path: test_results
workflows:
  version: 2
  tests:
    jobs:
      - test
