# Based on https://qxf2.com/blog/tox-with-circleci/
version: 2
jobs:
  test:
      docker:
        - image: circleci/python:3.7.5
      steps:
        - checkout
        - run: pip install -r requirements.txt --user
        - run: pytest -s --junitxml=test_results/pytest/pytest-report.xml
        - store_test_results:
+          path: test_results
workflows:
  version: 2
  myproj:
    jobs:
      - test
