# Based on https://qxf2.com/blog/tox-with-circleci/
version: 2

jobs:

  toxify:

      docker:
        - image: circleci/python:3.7.5
      steps:
        - checkout
        - run: sudo pip install tox
        - run: tox

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
